### ISSUE TITLE
Please add a license and copyright statement

### ISSUE THREAD

**Issue by sunweaver** [pengutronix/monitoring-check-dirvish#1]
Hi Björn,

awesome little project!!! Thanks for providing it in public.

For making your code reusable (which I hope is intended), please add a license (e.g. MIT/Expat, Apache2, GPL-2+, etc.) and add copyright information to README.md.

The license should be shipped in full text in a file named COPYING or LICENSE.

Thanks!
Mike (Debian Developer who has been using dirvish for ages, too)

**Comment by Farom** [comment]
I added a 0-Clause BSD licence. I hope it fits youre needs.
